<a href="https://colab.research.google.com/github/reyhan1997/Transaction-data-exploration/blob/main/transactions_explore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
url = 'https://raw.githubusercontent.com/reyhan1997/Transaction-data-exploration/refs/heads/main/Transactions.csv'
import numpy as np
import pandas as pd
df = pd.read_csv(url)

In [3]:
df.head()

,TransactionID,OrderNumber,LineItem,OrderDate,DeliveryDate,Quantity,CustomerID,CustomerGender,CustomerName,CustomerCity,...,ProductID,ProductName,ProductBrand,ProductColor,ProductCost,ProductPrice,ProductSubcategoryID,ProductSubcategory,ProductCategoryID,ProductCategory
0,3660001,366000,1,1/1/2016,NaN,1,265598,Male,Tyler Vaught,London,...,1304,Contoso Lens Adapter M450 White,Contoso,White,$31.27,$68.00,406,Cameras & Camcorders Accessories,4,Cameras and camcorders
1,3660011,366001,1,1/1/2016,1/13/2016,2,1269051,Male,Frank Upchurch,Auberry,...,1048,A. Datum SLR Camera X136 Silver,A. Datum,Silver,$141.47,$427.00,402,Digital SLR Cameras,4,Cameras and camcorders
2,3660012,366001,2,1/1/2016,1/13/2016,1,1269051,Male,Frank Upchurch,Auberry,...,2007,Fabrikam Microwave 1.5CuFt X1100 Black,Fabrikam,Black,$220.64,$665.94,803,Microwaves,8,Home Appliances
3,3660021,366002,1,1/1/2016,1/12/2016,7,266019,Female,Joan Roche,Red Deer,...,1106,Contoso SLR Camera M146 Orange,Contoso,Orange,$148.08,$322.00,402,Digital SLR Cameras,4,Cameras and camcorders
4,3660022,366002,2,1/1/2016,1/12/2016,1,266019,Female,Joan Roche,Red Deer,...,373,Adventure Works Laptop8.9 E0890 White,Adventure Works,White,$166.20,$326.00,301,Laptops,3,Computers

In [5]:
df.shape

(62884, 31)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62884 entries, 0 to 62883
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   TransactionID         62884 non-null  int64
 1   OrderNumber           62884 non-null  int64
 2   LineItem              62884 non-null  int64
 3   OrderDate             62884 non-null  object
 4   DeliveryDate          13165 non-null  object
 5   Quantity              62884 non-null  int64
 6   CustomerID            62884 non-null  int64
 7   CustomerGender        62884 non-null  object
 8   CustomerName          62884 non-null  object
 9   CustomerCity          62884 non-null  object
 10  CustomerStateCode     62854 non-null  object
 11  CustomerState         62884 non-null  object
 12  CustomerZip           62884 non-null  object
 13  CustomerCountry       62884 non-null  object
 14  CustomerContinent     62884 non-null  object
 15  CustomerDOB           62884 non-null  object
 16  StoreID               62884 non-null  int64
 17  StoreCountry          62884 non-null  object
 18  StoreState            62884 non-null  object
 19  StoreSqMeters         62884 non-null  int64
 20  StoreOpenDate         62884 non-null  object
 21  ProductID             62884 non-null  int64
 22  ProductName           62884 non-null  object
 23  ProductBrand          62884 non-null  object
 24  ProductColor          62884 non-null  object
 25  ProductCost           62884 non-null  object
 26  ProductPrice          62884 non-null  object
 27  ProductSubcategoryID  62884 non-null  int64
 28  ProductSubcategory    62884 non-null  object
 29  ProductCategoryID     62884 non-null  int64
 30  ProductCategory       62884 non-null  object
dtypes: int64(10), object(21)
memory usage: 14.9+ MB

In [20]:
df.isnull().sum()

TransactionID               0
OrderNumber                 0
LineItem                    0
OrderDate                   0
DeliveryDate            49719
Quantity                    0
CustomerID                  0
CustomerGender              0
CustomerName                0
CustomerCity                0
CustomerStateCode          30
CustomerState               0
CustomerZip                 0
CustomerCountry             0
CustomerContinent           0
CustomerDOB                 0
StoreID                     0
StoreCountry                0
StoreState                  0
StoreSqMeters               0
StoreOpenDate               0
ProductID                   0
ProductName                 0
ProductBrand                0
ProductColor                0
ProductCost                 0
ProductPrice                0
ProductSubcategoryID        0
ProductSubcategory          0
ProductCategoryID           0
ProductCategory             0
dtype: int64

In [35]:
df['CustomerGender'].value_counts("Female")

CustomerGender
Male      0.505757
Female    0.494243
Name: proportion, dtype: float64

In [42]:
df['ProductPrice'] = df['ProductPrice'].astype(str).str.replace('$', '', regex=False)
df['ProductPrice'] = pd.to_numeric(df['ProductPrice'], errors='coerce')

# Display the data types to confirm the change
display(df['ProductPrice'].dtype)

dtype('float64')

In [41]:
# Check for any missing values introduced by the conversion
display(df['ProductPrice'].isnull().sum())

np.int64(2185)

In [43]:
# Display rows where 'ProductPrice' is NaN to understand the original values
display(df[df['ProductPrice'].isnull()][['ProductPrice', 'ProductCost']].head())

    ProductPrice ProductCost
6            NaN     $527.53
27           NaN     $331.32
41           NaN   $1,060.22
51           NaN     $960.82
67           NaN   $1,060.22

In [44]:
display(df['ProductCategory'].unique())

array(['Cameras and camcorders', 'Home Appliances', 'Computers',
       'TV and Video', 'Cell phones', 'Music, Movies and Audio Books',
       'Games and Toys', 'Audio'], dtype=object)